### ISSUE TITLE
Atlaskit with Re-frame

### ISSUE THREAD

**Issue by renanpalmeira** [mitchelkuijpers/cljs-atlaskit-node-modules#1]
I also trying using node modules with clojurescript and reframe, but without success yet... Do you going push your code here ? or still trying ?

Thanks

**Comment by mitchelkuijpers** [comment]
Yes I will push my code here trying to get it working

**Comment by mitchelkuijpers** [comment]
I pushed some code it seems to me the errors are originating from the styled-components library. If you got further or have suggestions please let me know.

**Comment by renanpalmeira** [comment]
Hi @mitchelkuijpers,

I not get solved your error, but i discovery in lastest version (https://github.com/bhauman/lein-figwheel/releases) of figwheel template if use :npm-deps, the import e.g. style-components run.

Components of atlaskit, have a "@" (in npm have a name "scoped packages") the actual clojurescript compiler version not implemented/updated this feature (yet). https://dev.clojure.org/jira/browse/CLJS-2226

Sorry for the delay in reply
